### ISSUE TITLE
As a user, I want encrypted key meta and names so I don't leak details about my secrets (also add value versioning)

### ISSUE THREAD

**Issue by thequailman** [candiddev/rot#11]
## Requirements
- [x] Add flag to toggle keyring value name encryption
- [x] Add flag to toggle keyring value meta encryption
- [x] Encrypt keyring value names if toggle is set
- [x] Encrypt keyring meta if toggle is set
- [x] Add value versioning for duplicate key names
  - [x] value paths can reference a version via @: `keyring/value@2024`
  - [x] The time value after it is ISO but filtered from left to right:
    - [x] @2024 means the latest value from 2024
    - [x] @202404 means the latest value from april 2024
    - [x] etc
- [x] Adjust keyring path parsing to lookup version
- [x] Have the version lookup work for unencrypted values
